import { Status, type MeetTrack } from "./models";

export const meetTrackList: MeetTrack[] = [
  {
    id: 1,
    customer_name: "ABC",
    contact_name: "John Doe",
    designation: "Manager",
    zone: "North",
    location: "New York",
    spoc: "Jane Smith",
    requester: "CVK",
    objective: "Discuss project",
    remarks: "Follow up",
    status: Status.APPROVED,
    meeting_date: new Date("2024-08-15"),
  },
  {
    id: 2,
    customer_name: "Dell",
    contact_name: "Emma Brown",
    designation: "Director",
    zone: "West",
    location: "San Francisco",
    spoc: "Mike Wilson",
    requester: "CVK",
    objective: "Budget planning",
    remarks: "financial reports",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-09-10"),
  },
  {
    id: 3,
    customer_name: "XYZ Corp",
    contact_name: "Ram Sharma",
    designation: "Tech Lead",
    zone: "South",
    location: "New Delhi",
    spoc: "Ravi Kumar",
    requester: "Sita",
    objective: "Product demo",
    remarks: "Lorem ipsum.",
    status: Status.DECLINED,
  },
  {
    id: 4,
    customer_name: "Google",
    contact_name: "Amit Verma",
    designation: "VP",
    zone: "East",
    location: "Mumbai",
    spoc: "Nisha Patel",
    requester: "CVK",
    objective: "Tech partnership",
    remarks: "Call scheduled",
    status: Status.APPROVED,
    meeting_date: new Date("2024-09-12"),
  },
  {
    id: 5,
    customer_name: "Microsoft",
    contact_name: "Sarah Johnson",
    designation: "CEO",
    zone: "North",
    location: "Chicago",
    spoc: "Arjun Singh",
    requester: "CVK",
    objective: "Collaborate",
    remarks: "Urgent",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-08-20"),
  },
  {
    id: 6,
    customer_name: "Infosys",
    contact_name: "Anil Kumar",
    designation: "Manager",
    zone: "South",
    location: "Bengaluru",
    spoc: "Priya Sharma",
    requester: "RJ",
    objective: "Hiring discussion",
    remarks: "Pending approval",
    status: Status.DECLINED,
  },
  {
    id: 7,
    customer_name: "Amazon",
    contact_name: "Vikas Gupta",
    designation: "Senior Manager",
    zone: "West",
    location: "Seattle",
    spoc: "Rohit Agarwal",
    requester: "CVK",
    objective: "AWS Services",
    remarks: "Review proposal",
    status: Status.APPROVED,
    meeting_date: new Date("2024-11-05"),
  },
  {
    id: 8,
    customer_name: "TCS",
    contact_name: "Pooja Singh",
    designation: "Tech Consultant",
    zone: "North",
    location: "Gurugram",
    spoc: "Rahul Jain",
    requester: "Sita",
    objective: "Client onboarding",
    remarks: "Documentation pending",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-07-22"),
  },
  {
    id: 9,
    customer_name: "Apple",
    contact_name: "John Carter",
    designation: "Director",
    zone: "West",
    location: "Cupertino",
    spoc: "Karan Patel",
    requester: "CVK",
    objective: "Product launch",
    remarks: "VIP visit",
    status: Status.APPROVED,
  },
  {
    id: 10,
    customer_name: "Oracle",
    contact_name: "Rohan Tina",
    designation: "Manager",
    zone: "North",
    location: "London",
    spoc: "Tina",
    requester: "CVK",
    objective: "Meeting",
    remarks: "None",
    status: Status.APPROVED,
    meeting_date: new Date("2024-01-10"),
  },
  {
    id: 11,
    customer_name: "Wipro",
    contact_name: "Priya Dev",
    designation: "Lead",
    zone: "South",
    location: "Pune",
    spoc: "Dev",
    requester: "RJ",
    objective: "Follow Up",
    remarks: "High Priority",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-02-11"),
  },
  {
    id: 12,
    customer_name: "Meta",
    contact_name: "Sam Neha",
    designation: "VP",
    zone: "East",
    location: "Hyderabad",
    spoc: "Neha",
    requester: "CVK",
    objective: "Project Discussion",
    remarks: "Discuss internally",
    status: Status.DECLINED,
  },
  {
    id: 13,
    customer_name: "Adobe",
    contact_name: "Ajay Sonia",
    designation: "Consultant",
    zone: "West",
    location: "Delhi",
    spoc: "Sonia",
    requester: "CVK",
    objective: "Budget",
    remarks: "Pending docs",
    status: Status.APPROVED,
    meeting_date: new Date("2024-03-13"),
  },
  {
    id: 14,
    customer_name: "Tesla",
    contact_name: "Lata Ajay",
    designation: "Analyst",
    zone: "North",
    location: "Ahmedabad",
    spoc: "Ajay",
    requester: "RJ",
    objective: "Demo",
    remarks: "None",
    status: Status.PROPOSED,
  },
  {
    id: 15,
    customer_name: "HCL",
    contact_name: "Kunal Sam",
    designation: "Manager",
    zone: "South",
    location: "Tokyo",
    spoc: "Sam",
    requester: "CVK",
    objective: "Meeting",
    remarks: "High Priority",
    status: Status.APPROVED,
    meeting_date: new Date("2024-04-15"),
  },
  {
    id: 16,
    customer_name: "Cisco",
    contact_name: "Sonia Tina",
    designation: "Lead",
    zone: "East",
    location: "Dubai",
    spoc: "Tina",
    requester: "Sita",
    objective: "Follow Up",
    remarks: "Pending docs",
    status: Status.PROPOSED,
  },
  {
    id: 17,
    customer_name: "Capgemini",
    contact_name: "Dev Rohan",
    designation: "VP",
    zone: "West",
    location: "Melbourne",
    spoc: "Rohan",
    requester: "CVK",
    objective: "Project Discussion",
    remarks: "Discuss internally",
    status: Status.DECLINED,
  },
  {
    id: 18,
    customer_name: "Deloitte",
    contact_name: "Tina Priya",
    designation: "Consultant",
    zone: "North",
    location: "Paris",
    spoc: "Priya",
    requester: "CVK",
    objective: "Budget",
    remarks: "None",
    status: Status.APPROVED,
    meeting_date: new Date("2024-05-18"),
  },
  {
    id: 19,
    customer_name: "SAP",
    contact_name: "Neha Dev",
    designation: "Analyst",
    zone: "South",
    location: "London",
    spoc: "Dev",
    requester: "RJ",
    objective: "Demo",
    remarks: "High Priority",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-06-19"),
  },
  {
    id: 20,
    customer_name: "Oracle",
    contact_name: "Rohan Tina",
    designation: "Manager",
    zone: "East",
    location: "Pune",
    spoc: "Tina",
    requester: "CVK",
    objective: "Meeting",
    remarks: "None",
    status: Status.APPROVED,
  },
  {
    id: 21,
    customer_name: "Wipro",
    contact_name: "Priya Dev",
    designation: "Lead",
    zone: "West",
    location: "Hyderabad",
    spoc: "Dev",
    requester: "RJ",
    objective: "Follow Up",
    remarks: "High Priority",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-07-21"),
  },
  {
    id: 22,
    customer_name: "Meta",
    contact_name: "Sam Neha",
    designation: "VP",
    zone: "North",
    location: "Delhi",
    spoc: "Neha",
    requester: "CVK",
    objective: "Project Discussion",
    remarks: "Discuss internally",
    status: Status.DECLINED,
  },
  {
    id: 23,
    customer_name: "Adobe",
    contact_name: "Ajay Sonia",
    designation: "Consultant",
    zone: "South",
    location: "Ahmedabad",
    spoc: "Sonia",
    requester: "CVK",
    objective: "Budget",
    remarks: "Pending docs",
    status: Status.APPROVED,
    meeting_date: new Date("2024-08-23"),
  },
  {
    id: 24,
    customer_name: "Tesla",
    contact_name: "Lata Ajay",
    designation: "Analyst",
    zone: "East",
    location: "Tokyo",
    spoc: "Ajay",
    requester: "RJ",
    objective: "Demo",
    remarks: "None",
    status: Status.PROPOSED,
  },
];

export const headerData: string[] = [
  "Customer Name",
  "Contact Name",
  "Designation",
  "Zone",
  "Location",
  "SPOC",
  "Requester",
  "Objective",
  "Remarks",
  "Status",
  "Meeting Date",
  "Action",
];
