import { Status, type MeetTrack } from "./models";

export const meetTrackList: MeetTrack[] = [
  {
    id: 1,
    customer_name: "ABC",
    contact_name: "John Doe",
    designation: "Manager",
    zone: "North",
    location: "New York",
    spoc: "Jane Smith",
    requester: "CVK",
    objective: "Discuss project",
    remarks: "Follow up",
    status: Status.APPROVED,
    meeting_date: new Date("2024-08-15"),
  },
  {
    id: 2,
    customer_name: "Dell",
    contact_name: "Emma Brown",
    designation: "Director",
    zone: "West",
    location: "San Francisco",
    spoc: "Mike Wilson",
    requester: "CVK",
    objective: "Budget planning",
    remarks: "financial reports",
    status: Status.PROPOSED,
    meeting_date: new Date("2024-09-10"),
  },
  {
    id: 3,
    customer_name: "XYZ Corp",
    contact_name: "Ram Sharma",
    designation: "Tech Lead",
    zone: "South",
    location: "New Delhi",
    spoc: "Ravi Kumar",
    requester: "Sita",
    objective: "Product demo",
    remarks: "Lorem ipsum.",
    status: Status.DECLINED,
  },
];

export const headerData: string[] = [
  "Customer Name",
  "Contact Name",
  "Designation",
  "Zone",
  "Location",
  "SPOC",
  "Requester",
  "Objective",
  "Remarks",
  "Status",
  "Meeting Date",
  "Action",
];
